"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useDialogState } from "@/lib/use-dialog-state";
import { t } from "@/lib/i18n";
import { DeleteButton, type Mutate } from "./directory-tools";

type User = { id: string; name: string; role: string; username?: string | null; email?: string; disabledAt?: string | null; teacherName?: string | null; studentName?: string | null };
export function AccountDirectory({ users, actor, teachers, students, mutate, busy, createForm }: { users: User[]; actor: { id?: string; isOwner?: boolean }; teachers: string[]; students: string[]; mutate: Mutate; busy: boolean; createForm: React.ReactNode }) {
  const [search, setSearch] = useState(""), [removed, setRemoved] = useState(false);
  const [editing, setEditing] = useDialogState<User | null>("account-edit", null);
  const [create, setCreate] = useDialogState<boolean | null>("account-create", null);
  const [role, setRole] = useState("teacher"), [identity, setIdentity] = useState("");
  const visible = users.filter(u => Boolean(u.disabledAt) === removed && `${u.name} ${u.email || ""} ${u.username || ""} ${u.teacherName || ""} ${u.studentName || ""}`.toLowerCase().includes(search.toLowerCase()));
  function edit(u: User) { setRole(u.role === "pending" ? "teacher" : u.role); setIdentity(u.teacherName || u.studentName || ""); setEditing(u); }
  return <section className="panel"><div className="section-head"><h2>{t("账号管理")}</h2><Button onClick={() => setCreate(true)}>{t("创建登录账号")}</Button></div>
    <div className="directory-filters"><label>{t("搜索账号")}<input value={search} onChange={e => setSearch(e.target.value)} placeholder={t("姓名、登录账号或邮箱")}/></label><label>{t("显示记录")}<select value={removed ? "removed" : "active"} onChange={e => setRemoved(e.target.value === "removed")}><option value="active">{t("启用")}</option><option value="removed">{t("已停用账号")}</option></select></label></div>
    {[["admin", "管理员"], ["teacher", "老师"], ["student", "学生"], ["pending", "待绑定"]].map(([r, label]) => <details className="directory-group" key={r} open={r === "pending" || Boolean(search)}><summary>{t(label)} <span>{visible.filter(u => u.role === r).length}</span></summary>{visible.filter(u => u.role === r).map(u => <article key={u.id} className="user-row"><div><strong>{u.name}</strong>{u.teacherName && <small>{t("关联老师")} · {u.teacherName}</small>}{u.studentName && <small>{t("关联学生")} · {u.studentName}</small>}<small>{u.username ? `${t("登录账号")} · ${u.username}` : t("未设置密码登录")}</small><small>{u.email ? `Google · ${u.email}` : t("未连接 Google")}</small></div><div className="user-actions">{u.id !== actor.id && u.email !== "felixtey2016@gmail.com" && (u.role !== "admin" || actor.isOwner) && <>{!u.disabledAt && <Button size="sm" variant="outline" onClick={() => edit(u)}>{t("身份设置")}</Button>}<Button disabled={busy} size="sm" variant="outline" onClick={() => { if (u.disabledAt || window.confirm(t("停用后此账号不能登录，可以稍后恢复。"))) void mutate({ action: u.disabledAt ? "restoreAccount" : "deleteAccount", userId: u.id }); }}>{t(u.disabledAt ? "恢复" : "停用")}</Button><DeleteButton kind="account" id={u.id} mutate={mutate} busy={busy} message="永久删除账号及其登录方式和个人学习安排？历史课程会保留；若拥有功课或教学资料，需先处理。"/></>}</div></article>)}</details>)}
    <Dialog open={Boolean(create)} onOpenChange={open => setCreate(open ? true : null)}><DialogContent className="lesson-dialog directory-dialog"><DialogHeader><DialogTitle>{t("创建登录账号")}</DialogTitle></DialogHeader>{createForm}</DialogContent></Dialog>
    <Dialog open={Boolean(editing)} onOpenChange={open => { if (!open) setEditing(null); }}><DialogContent className="lesson-dialog"><DialogHeader><DialogTitle>{t("身份设置")}</DialogTitle></DialogHeader><p>{editing?.name} · {editing?.email || editing?.username}</p><form onSubmit={async e => { e.preventDefault(); if (await mutate({ action: "bind", userId: editing?.id, role, teacherName: role === "teacher" ? identity : "", studentName: role === "student" ? identity : "" })) setEditing(null); }}><label>{t("角色")}<select value={role} onChange={e => { setRole(e.target.value); setIdentity(""); }}><option value="teacher">{t("老师")}</option><option value="student">{t("学生")}</option><option value="admin">{t("管理员")}</option></select></label>{role !== "admin" && <label>{t(role === "teacher" ? "关联老师" : "关联学生")}<select required value={identity} onChange={e => setIdentity(e.target.value)}><option value="">{t("请选择")}</option>{(role === "teacher" ? teachers : students).map(n => <option key={n}>{n}</option>)}</select></label>}<Button disabled={busy}>{t("确认绑定")}</Button></form></DialogContent></Dialog>
  </section>;
}
