import { BRAND_NAME } from "./brand";

export const LEGAL_VERSION = "2026-10-07.1";
export const SERVICE_OPERATOR = "Tey Ze Zhou";
export const LEGAL_CONTACT = "felixtey2016@gmail.com";
export type LegalLanguage = "zh" | "en" | "ms";
export type LegalSection = { title: string; paragraphs: string[] };
export type LegalCopy = { title: string; summary: string; sections: LegalSection[] };

export const termsContent: Record<"zh" | "en", LegalCopy> = {
  zh: {
    title: "服务条款",
    summary: `${BRAND_NAME} 是用于学习安排、课程协作、作业与教学资料管理的平台。请在使用前阅读本条款及隐私政策。`,
    sections: [
      { title: "1. 服务与适用范围", paragraphs: [`${BRAND_NAME} 由 ${SERVICE_OPERATOR} 运营。本条款适用于学生、老师、管理员及经授权使用学生账号的家长或监护人。`, "平台提供课程安排、出席记录、改期申请、班级公告、资料分配、作业提交及个人学习日历等功能。能使用的功能和查看的资料取决于账号角色及管理员的分配。"] },
      { title: "2. 账号与未成年用户", paragraphs: ["请提供准确的姓名及账号资料，并妥善保管密码。只使用属于你或已获明确授权的账号；家长或监护人可在学生及相关服务提供者允许的情况下，协助使用学生账号。请勿转让、出售账号或冒充他人。", "未成年学生应在家长或监护人知情和适当协助下使用服务。为学生建立账号或上传其资料的老师、管理员及监护人，应确保拥有适当的授权，并只提供学习所需的资料。", "Google 登录受 Google 的相关条款约束。网站账号的角色不代表已取得外部会议或第三方服务的权限。"] },
      { title: "3. 课程、出席与作业", paragraphs: ["课程以平台当前确认的时间为准，日期与时间按马来西亚时间（GMT+8）显示。需要对方确认的改期申请，在获接受前不会改变已确认的上课时间。", "出席由获授权的老师或管理员记录；仅到达课程时间、打开上课链接或进入个人学习安排，不代表已完成上课。发现记录错误时，请联系相关老师或管理员核实。", "作业按发布的开始及截止时间处理。迟交、替换提交及可选分数依平台显示的规则执行。个人学习安排仅用于规划，不计入正式课时，也不会自动提交作业。"] },
      { title: "4. 内容与合理使用", paragraphs: ["上传资料、作业、公告及其他内容时，你应拥有相关权利或已获许可。内容的知识产权仍归原权利人；你允许平台仅为储存、备份及向获分配的用户提供访问而处理这些内容。", "教学资料仅可在获许可的范围内使用。未经许可，不得公开传播他人的文件、联系方式或学习记录。请勿上传违法、侵犯隐私或版权、有害的内容，也不得尝试绕过访问权限或干扰平台。", "当前文件上传仅接受 PDF，单份上限为 10 MB，以上传界面公布的限制为准。请保留重要文件的自己的副本。"] },
      { title: "5. 外部服务与费用", paragraphs: ["上课链接可能指向 Google Meet 或其他外部服务，这些服务有各自的条款及可用性限制。平台显示链接本身不保证会议已经开始或有人参与。", "课程费用、收费课程的取消或退款安排、老师报酬及其他服务费用，应由相关服务提供者和用户另行明确约定；本页面不会替代这些约定。"] },
      { title: "6. 记录、停用与删除", paragraphs: ["管理员可按权限分配角色、停用账号或处理删除请求。涉及安全、违规或他人资料的情况，运营者可限制相关访问；如有争议，可通过下方邮箱联系运营者。", "停用或归档不等于永久删除。删除账号也不一定会删除与其他用户共同关联的课程、出席或业务记录；备份可能仍包含此前的数据。具体处理范围请参阅隐私政策或向运营者查询。"] },
      { title: "7. 可用性、责任与更新", paragraphs: ["网络、设备及外部服务可能影响平台使用。平台会尽合理努力处理问题，但不保证持续无中断或所有记录完全无误。请及时报告问题，并自行保留需要长期保存的资料。", "本条款不排除适用法律下不能被排除的用户权利或运营者责任。平台功能或条款调整会以更新版本说明；重大变更应在适用前向受影响用户说明。", `条款或服务问题请联系 ${SERVICE_OPERATOR}：${LEGAL_CONTACT}。`] },
    ],
  },
  en: {
    title: "Terms and Conditions",
    summary: `${BRAND_NAME} is a platform for learning plans, lesson collaboration, assignments and teaching resources. Please read these terms and the Privacy Policy before using it.`,
    sections: [
      { title: "1. Service and scope", paragraphs: [`${BRAND_NAME} is operated by ${SERVICE_OPERATOR}. These terms apply to students, teachers, administrators and parents or guardians authorised to use a student's account.`, "The platform supports scheduling, attendance records, rescheduling requests, classroom announcements, resource assignments, homework submissions and personal study plans. Available functions and records depend on your account role and administrator assignments."] },
      { title: "2. Accounts and younger users", paragraphs: ["Provide accurate names and account details and keep passwords secure. Use only your own account or one you are expressly authorised to use. Parents or guardians may assist through a student's account with the permission of the student and relevant service provider. Do not transfer or sell accounts or impersonate others.", "Students who are minors should use the service with their parent's or guardian's knowledge and appropriate assistance. Teachers, administrators and guardians who create student accounts or provide their information must have appropriate authority and provide only information needed for learning.", "Google sign-in is subject to Google's terms. A website role does not itself grant access to external meetings or third-party services."] },
      { title: "3. Lessons, attendance and assignments", paragraphs: ["The currently confirmed schedule governs lesson times. Dates and times are shown in Malaysia time (GMT+8). A rescheduling request requiring the other participant's approval does not change the confirmed time until accepted.", "Authorised teachers or administrators record attendance. Reaching a scheduled time, opening a meeting link or creating a personal study plan does not mean a lesson has been completed. Ask the relevant teacher or administrator to investigate incorrect records.", "Assignment start and due times apply as published. Late submissions, replacements and optional marks follow the rules displayed in the platform. Personal study plans do not count as lesson hours or automatically submit homework."] },
      { title: "4. Content and acceptable use", paragraphs: ["You must have the rights or permission needed to upload resources, homework, announcements and other content. Intellectual property remains with its rights holders. You allow the platform to process content only to store, back up and provide it to authorised recipients.", "Use teaching resources only within the permission granted. Do not publish another person's files, contact details or learning records without permission. Do not upload unlawful, harmful, privacy-infringing or copyright-infringing content, bypass access controls or disrupt the platform.", "Uploads currently accept PDFs only, with a limit of 10 MB per file, subject to the limits shown in the upload interface. Keep your own copies of important files."] },
      { title: "5. External services and fees", paragraphs: ["Lesson links may open Google Meet or other external services with their own terms and availability limits. Displaying a link does not guarantee that a meeting has started or that someone is present.", "Lesson fees, paid-lesson cancellation or refund arrangements, teacher remuneration and other service charges must be clearly agreed separately between the relevant provider and user. This page does not replace those agreements."] },
      { title: "6. Records, suspension and deletion", paragraphs: ["Administrators may assign roles, disable accounts or process deletion requests within their permissions. The operator may restrict access for security, misuse or protection of others' information. Contact the operator below if you dispute a restriction.", "Disabling or archiving is not permanent deletion. Deleting an account may not remove lesson, attendance or business records shared with others, and backups may retain earlier data. Consult the Privacy Policy or contact the operator for the scope of a request."] },
      { title: "7. Availability, responsibility and updates", paragraphs: ["Networks, devices and external services can affect access. Reasonable efforts will be made to address problems, but uninterrupted service and completely error-free records are not guaranteed. Report issues promptly and retain your own copies of records you need long term.", "These terms do not exclude user rights or operator responsibilities that cannot be excluded under applicable law. Feature or terms changes will be identified through updated versions; affected users should be informed of material changes before they apply.", `For terms or service questions, contact ${SERVICE_OPERATOR} at ${LEGAL_CONTACT}.`] },
    ],
  },
};

export const privacyContent: Record<LegalLanguage, LegalCopy> = {
  zh: {
    title: "隐私政策",
    summary: `本政策说明 ${BRAND_NAME} 如何处理学习服务中的个人资料。运营者为 ${SERVICE_OPERATOR}，联系邮箱为 ${LEGAL_CONTACT}。`,
    sections: [
      { title: "1. 资料类型与来源", paragraphs: ["我们处理你、老师、管理员或经授权的监护人提供的姓名、登录邮箱或用户名、账号角色、课程与科目分配，以及课程时间、出席、改期、班级成员与公告、教学资料、作业、提交时间和可选分数。个人学习安排包括你输入的标题、时间、科目及备注。", "Google 登录提供经验证的 Google 账号标识、邮箱及姓名。密码以哈希形式保存，而非明文。上传文件会包含文件内容、文件名、大小及归属资料；请勿在文件名或内容中加入不必要的私人信息。"] },
      { title: "2. 处理目的与必需资料", paragraphs: ["这些资料用于验证登录、分配访问权限、提供学习功能、保存记录、处理课时同步、保障账号安全、解决问题及备份恢复。登录及对应服务所需的资料为必需；缺少这些资料可能无法登录或使用相关功能。标为可选的说明、备注或附件可不提供。"] },
      { title: "3. 谁可以查看", paragraphs: ["学生可查看分配给自己的课程、资料、作业及相关班级内容；老师可按负责学生、班级及上传归属查看相关记录；管理员和运营者可为分配、支持、安全及维护处理所需记录。个人学习安排不向其他学生或老师展示。经授权共用学生账号的家长可查看该账号可访问的内容。", "Google Sheet 同步由获授权的管理员发起，将相应课时及配对姓名、科目等资料发送到已配置的表格；该表格之后的访问权限由表格所有者管理。"] },
      { title: "4. 储存、第三方与跨境处理", paragraphs: ["网站使用 OpenAI Sites 托管，以及 Cloudflare 提供的数据库和私有文件储存。Google 用于 Google 登录和已配置的表格同步；加密备份可存放在运营者控制的电脑及 Google Drive 中。这些提供者可能在马来西亚以外处理数据，具体基础设施位置由提供者决定。", "当你打开外部会议或其他链接时，相应服务会按其自身隐私政策处理资料。网站托管及第三方服务也可能为安全和运行记录 IP、浏览器或请求资料；本平台不会把此类技术记录展示成课堂出席证明。"] },
      { title: "5. Cookie 与设备偏好", paragraphs: ["网站使用登录 Cookie 保持会话，并在浏览器本地保存语言、筛选和界面偏好。清除或禁用这些储存可能使你需要重新登录或重新设置偏好。Google 登录及外部服务有各自的 Cookie 和隐私规则。"] },
      { title: "6. 保存、删除与安全", paragraphs: ["资料按学习服务、记录核实、安全、备份及适用要求所需保留。停用、归档及永久删除是不同操作；与其他用户关联的记录及现有备份可能不会随账号删除一并移除。可联系运营者了解具体保留原因与删除范围。", "我们使用账号权限、私有文件访问控制及加密备份等措施，但不能保证任何系统绝对安全。请保护账号并保留重要资料的副本。"] },
      { title: "7. 查询、更正与选择", paragraphs: [`如需查询、更正、删除资料或撤回适用的授权，请联系 ${LEGAL_CONTACT}。为保护资料，我们可能需要核实身份，并说明处理结果及依法或因共同记录需要保留的范围。撤回必要授权可能影响相关服务。`, "家长或监护人可就未成年学生的资料提出请求，并配合身份与授权核实。老师及管理员不应收集或上传与学习无关的学生私人资料。"] },
      { title: "8. 政策更新", paragraphs: ["页面列明本政策的版本及更新日期。个人资料处理方式出现重大变化时，应先向受影响用户说明，并在适用情况下重新取得授权。"] },
    ],
  },
  en: {
    title: "Privacy Policy",
    summary: `This policy explains how ${BRAND_NAME} handles personal information for its learning services. The operator is ${SERVICE_OPERATOR}, contactable at ${LEGAL_CONTACT}.`,
    sections: [
      { title: "1. Information and sources", paragraphs: ["We process names, sign-in emails or usernames, roles, lesson and subject assignments, schedules, attendance, rescheduling, classroom membership and announcements, resources, homework, submission times and optional marks supplied by you, teachers, administrators or authorised guardians. Personal study plans include titles, times, subjects and notes you enter.", "Google sign-in provides a verified Google account identifier, email and name. Passwords are stored as hashes, not plain text. Uploaded files include content, filenames, sizes and ownership details. Avoid unnecessary private information in filenames or content."] },
      { title: "2. Purposes and required information", paragraphs: ["Information is used to verify sign-in, assign access, provide learning functions, maintain records, process lesson-hour synchronisation, protect accounts, resolve problems and support backup and recovery. Information needed for sign-in and the relevant service is required; withholding it may prevent access or use. Descriptions, notes or attachments marked optional can be omitted."] },
      { title: "3. Who can access information", paragraphs: ["Students can access their assigned lessons, resources, assignments and relevant classroom content. Teachers access records according to assigned students, classrooms and content ownership. Administrators and the operator can process records needed for assignments, support, security and maintenance. Personal study plans are not shown to other students or teachers. Parents authorised to share a student's account can access what that account can access.", "Google Sheet synchronisation is initiated by an authorised administrator and sends relevant lesson hours, matching names, subjects and related information to the configured spreadsheet. The spreadsheet owner manages subsequent access."] },
      { title: "4. Storage, providers and international processing", paragraphs: ["The website uses OpenAI Sites hosting and Cloudflare database and private file storage. Google provides Google sign-in and configured spreadsheet synchronisation. Encrypted backups may be stored on the operator's computers and in Google Drive. Providers may process data outside Malaysia; infrastructure locations are determined by the providers.", "Opening a meeting or another external link subjects information to that service's own privacy policy. Hosting and external providers may log IP addresses, browser or request information for security and operations. The platform does not present such technical logs as proof of lesson attendance."] },
      { title: "5. Cookies and device preferences", paragraphs: ["A sign-in cookie maintains your session. Language, filter and interface preferences are stored locally in your browser. Clearing or disabling storage may require signing in or setting preferences again. Google sign-in and external services have their own cookie and privacy rules."] },
      { title: "6. Retention, deletion and security", paragraphs: ["Information is retained as needed for learning services, record verification, security, backups and applicable requirements. Disabling, archiving and permanent deletion are different actions. Records linked to others and existing backups may not be removed when an account is deleted. Contact the operator for specific retention reasons and deletion scope.", "Measures include account permissions, private file access controls and encrypted backups, but no system is guaranteed to be completely secure. Protect your account and keep copies of important information."] },
      { title: "7. Requests and choices", paragraphs: [`To request access, correction or deletion, or withdraw applicable authorisation, contact ${LEGAL_CONTACT}. We may verify identity to protect information and explain the outcome and any records retained for applicable requirements or shared records. Withdrawing necessary authorisation may affect the corresponding service.`, "Parents or guardians may make requests about a minor student's information, subject to identity and authority verification. Teachers and administrators should not collect or upload private student information unrelated to learning."] },
      { title: "8. Policy updates", paragraphs: ["The page identifies its version and update date. Affected users should be informed before material changes to personal information handling apply, with renewed authorisation obtained where applicable."] },
    ],
  },
  ms: {
    title: "Dasar Privasi",
    summary: `Dasar ini menerangkan cara ${BRAND_NAME} mengendalikan maklumat peribadi untuk perkhidmatan pembelajaran. Pengendalinya ialah ${SERVICE_OPERATOR}, yang boleh dihubungi di ${LEGAL_CONTACT}.`,
    sections: [
      { title: "1. Maklumat dan sumber", paragraphs: ["Kami memproses nama, e-mel log masuk atau nama pengguna, peranan, penugasan pelajaran dan subjek, jadual, kehadiran, penjadualan semula, keahlian dan pengumuman kelas, bahan, kerja rumah, masa penyerahan dan markah pilihan yang diberikan oleh anda, guru, pentadbir atau penjaga yang diberi kuasa. Rancangan belajar peribadi merangkumi tajuk, masa, subjek dan nota yang anda masukkan.", "Log masuk Google memberikan pengecam akaun Google, e-mel dan nama yang disahkan. Kata laluan disimpan sebagai hash, bukan teks biasa. Fail yang dimuat naik merangkumi kandungan, nama fail, saiz dan maklumat pemilikan. Elakkan maklumat peribadi yang tidak diperlukan dalam nama atau kandungan fail."] },
      { title: "2. Tujuan dan maklumat wajib", paragraphs: ["Maklumat digunakan untuk mengesahkan log masuk, memberikan akses, menyediakan fungsi pembelajaran, menyimpan rekod, menyegerakkan jam pelajaran, melindungi akaun, menyelesaikan masalah serta menyokong sandaran dan pemulihan. Maklumat untuk log masuk dan perkhidmatan berkaitan adalah wajib; jika tidak diberikan, akses atau penggunaan mungkin tidak tersedia. Keterangan, nota atau lampiran yang ditandakan sebagai pilihan boleh ditinggalkan."] },
      { title: "3. Akses kepada maklumat", paragraphs: ["Pelajar boleh mengakses pelajaran, bahan, tugasan dan kandungan kelas yang diberikan kepada mereka. Guru mengakses rekod berdasarkan pelajar, kelas dan pemilikan kandungan yang ditugaskan. Pentadbir dan pengendali boleh memproses rekod yang diperlukan untuk penugasan, sokongan, keselamatan dan penyelenggaraan. Rancangan belajar peribadi tidak dipaparkan kepada pelajar lain atau guru. Ibu bapa yang dibenarkan berkongsi akaun pelajar boleh mengakses kandungan yang tersedia kepada akaun itu.", "Penyegerakan Google Sheet dimulakan oleh pentadbir yang diberi kuasa dan menghantar jam pelajaran, nama sepadan, subjek dan maklumat berkaitan ke hamparan yang dikonfigurasi. Pemilik hamparan menguruskan akses selepas itu."] },
      { title: "4. Penyimpanan, penyedia dan pemprosesan antarabangsa", paragraphs: ["Laman web menggunakan pengehosan OpenAI Sites serta pangkalan data dan penyimpanan fail peribadi Cloudflare. Google menyediakan log masuk Google dan penyegerakan hamparan yang dikonfigurasi. Sandaran disulitkan boleh disimpan pada komputer pengendali dan dalam Google Drive. Penyedia mungkin memproses data di luar Malaysia; lokasi infrastruktur ditentukan oleh penyedia.", "Apabila membuka pautan mesyuarat atau pautan luar lain, maklumat tertakluk kepada dasar privasi perkhidmatan itu. Penyedia pengehosan dan perkhidmatan luar mungkin merekodkan alamat IP, pelayar atau permintaan untuk keselamatan dan operasi. Platform tidak menggunakan log teknikal tersebut sebagai bukti kehadiran pelajaran."] },
      { title: "5. Kuki dan pilihan peranti", paragraphs: ["Kuki log masuk mengekalkan sesi anda. Pilihan bahasa, penapis dan antara muka disimpan secara tempatan dalam pelayar. Memadam atau menyahaktifkan penyimpanan mungkin memerlukan log masuk atau tetapan semula. Log masuk Google dan perkhidmatan luar mempunyai peraturan kuki dan privasi sendiri."] },
      { title: "6. Penyimpanan rekod, pemadaman dan keselamatan", paragraphs: ["Maklumat disimpan mengikut keperluan perkhidmatan pembelajaran, pengesahan rekod, keselamatan, sandaran dan keperluan yang terpakai. Penyahaktifan, pengarkiban dan pemadaman kekal adalah tindakan berbeza. Rekod berkaitan pengguna lain dan sandaran sedia ada mungkin tidak dipadam apabila akaun dipadam. Hubungi pengendali untuk sebab penyimpanan dan skop pemadaman tertentu.", "Langkah keselamatan termasuk kebenaran akaun, kawalan akses fail peribadi dan sandaran disulitkan, tetapi tiada sistem dijamin selamat sepenuhnya. Lindungi akaun anda dan simpan salinan maklumat penting."] },
      { title: "7. Permintaan dan pilihan", paragraphs: [`Untuk meminta akses, pembetulan atau pemadaman, atau menarik balik kebenaran yang terpakai, hubungi ${LEGAL_CONTACT}. Kami mungkin mengesahkan identiti untuk melindungi maklumat serta menerangkan hasil dan rekod yang disimpan bagi keperluan terpakai atau rekod bersama. Penarikan kebenaran yang diperlukan mungkin menjejaskan perkhidmatan berkaitan.`, "Ibu bapa atau penjaga boleh membuat permintaan tentang maklumat pelajar bawah umur, tertakluk kepada pengesahan identiti dan kuasa. Guru dan pentadbir tidak sepatutnya mengumpul atau memuat naik maklumat peribadi pelajar yang tidak berkaitan dengan pembelajaran."] },
      { title: "8. Kemas kini dasar", paragraphs: ["Halaman menyatakan versi dan tarikh kemas kini. Pengguna yang terjejas harus dimaklumkan sebelum perubahan penting pada pemprosesan maklumat peribadi berkuat kuasa, dengan kebenaran baharu diperoleh jika berkenaan."] },
    ],
  },
};

// Technical disclosure for optional notifications; lesson access and attendance
// rules are unchanged by optional notifications.
privacyContent.zh.sections.push({title:"9. 可选上课提醒",paragraphs:["开启通知后，我们保存此设备的推送地址、加密公钥、通知语言、提醒及已读记录，用于发送上课提醒。浏览器或设备的通知服务会处理推送；独立 Cloudflare 定时服务仅调用受保护的发送入口，不接收学生名单或文件。系统通知使用简短内容，不展示登录邮箱或其他学生资料。通知中心记录保留 90 天，加密备份的保留规则仍适用。", "每个设备可单独关闭通知；退出登录会移除该设备的推送注册。拒绝后，下次进入网站可能再次显示网站提醒，但浏览器已禁止通知时需要你自行在设置中允许。iPhone／iPad 可能需要先添加到主屏幕。通知不是课堂出席证明，也不保证准时送达。"]});
privacyContent.en.sections.push({title:"9. Optional lesson reminders",paragraphs:["When you enable notifications, we store this device's push endpoint, encryption public keys, notification language, reminder and read records to deliver lesson reminders. Your browser or device's push service processes delivery. A separate Cloudflare clock calls a protected dispatch endpoint without receiving student lists or files. System notifications use brief content without sign-in emails or other students' information. Notification Centre records are retained for 90 days; the existing encrypted-backup retention policy also applies.", "You can disable notifications on each device. Signing out removes that device's registration. After declining, a new visit may show the website reminder again; if your browser has blocked permission, you must change its settings yourself. iPhone/iPad may require adding the site to the Home Screen first. Notifications are not attendance evidence and delivery time is not guaranteed."]});
privacyContent.ms.sections.push({title:"9. Peringatan pelajaran pilihan",paragraphs:["Apabila pemberitahuan diaktifkan, kami menyimpan alamat push peranti, kunci penyulitan awam, bahasa, rekod peringatan dan status dibaca. Perkhidmatan push pelayar atau peranti memproses penghantaran. Pemasa Cloudflare yang berasingan hanya memanggil titik penghantaran terlindung tanpa menerima senarai pelajar atau fail. Pemberitahuan sistem tidak memaparkan e-mel log masuk atau maklumat pelajar lain. Rekod pusat pemberitahuan disimpan selama 90 hari; dasar sandaran disulitkan sedia ada turut terpakai.", "Pemberitahuan boleh dimatikan bagi setiap peranti. Log keluar membuang pendaftaran peranti itu. Selepas ditolak, lawatan baharu boleh memaparkan peringatan laman lagi; kebenaran yang disekat mesti diubah sendiri dalam tetapan pelayar. iPhone/iPad mungkin perlu menambah laman ke Skrin Utama. Pemberitahuan bukan bukti kehadiran dan masa penghantaran tidak dijamin."]});

export function legalLanguage(value: unknown, privacy = false): LegalLanguage {
  return value === "en" ? "en" : privacy && value === "ms" ? "ms" : "zh";
}

termsContent.zh.sections[1].paragraphs.push("Google 登录用户需要为同一平台账号设置用户名及密码。新注册且尚未获管理员确认启用或分配身份的账号，待分配期限为注册后 7 天；到期后限制访问并安排清理。已有账号及曾启用的账号不进入该自动删除范围。");
termsContent.en.sections[1].paragraphs.push("Google users set a username and password for the same platform account. New accounts awaiting administrator activation or identity assignment have a 7-day assignment period from registration. Access is restricted at expiry and cleanup is scheduled. Existing accounts and previously activated accounts are excluded from automatic deletion.");
privacyContent.zh.sections[5].paragraphs.push("新注册且未启用或绑定身份的账号在 7 天后到期。定时清理会删除该账号的 Google 登录关联、密码登录凭证、会话、个人资料及用户名占用；共享业务记录、必要安全事件和此前的加密备份不会因此被删除。现有自动清理任务依赖运营者的电脑运行，关机时会在恢复运行后处理；到期访问限制由服务器执行。管理员确认启用或完成身份绑定后，即使日后结束配对，也不会重新进入待分配删除机制。既有账号不自动删除。");
privacyContent.en.sections[5].paragraphs.push("New accounts that have not been activated or assigned an identity expire after 7 days. Scheduled cleanup removes their Google identity link, password credential, sessions, profile and username claim. Shared business records, necessary security events and earlier encrypted backups are retained. The current cleanup task depends on the operator's computer and catches up after it resumes; expiry restrictions are enforced by the server. Administrator activation or identity assignment permanently excludes an account from this expiry pool, even after an assignment ends. Existing accounts are excluded.");
privacyContent.ms.sections[5].paragraphs.push("Akaun baharu yang belum diaktifkan atau diberikan identiti tamat selepas 7 hari. Pembersihan berjadual memadam pautan identiti Google, kelayakan kata laluan, sesi, profil dan tuntutan nama pengguna. Rekod bersama, peristiwa keselamatan yang perlu dan sandaran disulitkan terdahulu dikekalkan. Tugas semasa bergantung pada komputer pengendali dan diteruskan selepas komputer beroperasi semula; sekatan tamat tempoh dikuatkuasakan oleh pelayan. Pengaktifan pentadbir atau penugasan identiti mengecualikan akaun secara kekal daripada pemadaman ini, termasuk selepas penugasan berakhir. Akaun sedia ada dikecualikan.");

privacyContent.zh.sections.push({"title":"10. 可选 Google Meet 上课记录","paragraphs":["老师可另行授权创建会议的 Google 账号，允许平台读取课程会议的开始、结束、参与者标识和加入／离开时间。授权与 Google 登录分开；不会读取录像、录音、转写或 Google Drive 文件。授权凭证在服务器加密保存，不向学生或其他老师公开。","平台仅使用明确的 Google 用户标识匹配课程中的老师和学生，不根据同名推测身份。学生只可读取自己的课程摘要及自己与老师的会话记录，无法查看其他学生的参与者资料。老师和管理员按现有课程权限核查记录。会议记录可能延迟；它们是核查参考，不自动确认出席、课时、收费或薪资。","老师可在 Meet 上课记录页面断开连接停止后续读取，也可在 Google 账号的第三方连接设置中撤销授权。已有课程检测记录及加密备份按现有保留规则处理；永久删除课程会删除关联检测记录。备份中的授权凭证仍为密文，运行时解密密钥独立保管；恢复时若没有密钥，老师需要重新授权。"]});
privacyContent.en.sections.push({"title":"10. Optional Google Meet lesson records","paragraphs":["Teachers may separately authorize the Google account that created their meetings so the platform can read lesson meeting start/end times, participant identifiers and join/leave times. This authorization is separate from Google sign-in. Recordings, audio, transcripts and Google Drive files are not accessed. Authorization credentials are encrypted on the server and are not exposed to students or other teachers.","Only exact Google user identifiers are used to match lesson teachers and students; names are not guessed. Students can read their own lesson summaries and their own and their teacher’s sessions, without other students’ participant information. Teachers and administrators review records within their existing lesson permissions. Meeting data may be delayed and is evidence for review; it does not automatically confirm attendance, hours, fees or salaries.","Teachers may disconnect on the Meet lesson records page to stop future access, or revoke the grant in their Google account’s third-party connections. Existing records and encrypted backups follow the existing retention rules; permanently deleting a lesson deletes its monitoring records. Backed-up authorization credentials remain encrypted and their runtime decryption key is held separately. If the key is unavailable during recovery, teachers must authorize again."]});
privacyContent.ms.sections.push({"title":"10. Rekod pelajaran Google Meet pilihan","paragraphs":["Guru boleh memberikan kebenaran berasingan melalui akaun Google yang mencipta mesyuarat untuk membaca masa mula/tamat, pengecam peserta dan masa masuk/keluar mesyuarat pelajaran. Kebenaran ini berasingan daripada log masuk Google. Rakaman, audio, transkripsi dan fail Google Drive tidak diakses. Kelayakan kebenaran disulitkan pada pelayan dan tidak didedahkan kepada pelajar atau guru lain.","Hanya pengecam pengguna Google yang tepat digunakan untuk memadankan guru dan pelajar, bukan tekaan nama. Pelajar hanya boleh membaca ringkasan pelajaran sendiri serta sesi sendiri dan guru tanpa maklumat peserta pelajar lain. Guru dan pentadbir menyemak rekod mengikut kebenaran pelajaran sedia ada. Data mungkin lewat dan digunakan untuk semakan; ia tidak mengesahkan kehadiran, jam, yuran atau gaji secara automatik.","Guru boleh memutuskan sambungan pada halaman rekod Meet untuk menghentikan akses seterusnya atau membatalkan kebenaran melalui sambungan pihak ketiga akaun Google. Rekod dan sandaran sedia ada tertakluk pada peraturan penyimpanan sedia ada. Pemadaman kekal pelajaran memadam rekod pengawasan berkaitan. Kelayakan dalam sandaran kekal disulitkan dan kunci penyahsulitan disimpan berasingan. Jika kunci tiada semasa pemulihan, guru perlu memberikan kebenaran semula."]});
